language: ruby
rvm:
- 2.1
script: jekyll build
branches:
  only:
  - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
deploy:
  provider: s3
  access_key_id: AKIAIAKJ37RL3SIUPG2Q
  secret_access_key:
    secure: TqACaBeuebRbn/uyde4yHcvbi8NTgBLGL8ZV6vUb8eAF1mNCZhjAVfeWmJ14T40NVsILMuyvyWiuQIhmxG+0SGLeB2Q7EdmhoDSr3O4VKAlfG7IrBukhC8zDmEV2qBxUOtNRTeJfpAHJyitWs6Cd+EhAjlKgPW7mZVae/pIwPRI=
  skip_cleanup: true
  bucket: aslearth.com
  endpoint: aslearth.com.s3-website-us-east-1.amazonaws.com
  region: us-east-1
  acl: public_read
  local-dir: _site
