language: ruby
rvm:
- 2.1
script: bundle exec jekyll build
branches:
  only:
  - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
deploy:
  provider: s3
  access_key_id: AKIAIE6VXPFAEOLXEPMQ
  secret_access_key:
    secure: ZV9BlOFQsB2NoUXRXk0P2R84bmbLPfuGsj3ob9MBKuI9FMObi2e7vVnxWPiqitAcWNwf7c1INmN8Qu05cIFfUnDO5eWDE2yFKNwk44g6oZF6OmnFcK4eyvil+vnric6G5OpBWzeJOZ5WYQa12HGLWnw5gynM6EDvo4IAGKPuC80=
  skip_cleanup: true
  bucket: aslearth.com
  endpoint: aslearth.com.s3-website-us-east-1.amazonaws.com
  region: us-east-1
  acl: public_read
  local-dir: _site
