language: ruby
rvm:
- 2.1
script: jekyll build
branches:
  only:
  - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
deploy:
  provider: s3
  access_key_id: AKIAIE6VXPFAEOLXEPMQ
  secret_access_key:
    secure: VuCiq1iYCDV7TG4BwVmeEZgt1H8tVDtqqNm5kRm3Z6rXaELwBPlm9klw8wATUgjZch7ZWeUl+LQ11HgCETfNrKD+yIpv9l5IYNSDoDwHvIpJaBWPLkBT9AtHSjpN+LQvZoh6H86mCt3Pbt9R/lvI+L1yDzL9bR5CGSJ/aLfzrjg=
  skip_cleanup: true
  bucket: aslearth.com
  endpoint: aslearth.com.s3-website-us-east-1.amazonaws.com
  region: us-east-1
  acl: public_read
  local-dir: _site


