language: ruby
rvm:
- 2.1
script: jekyll build
branches:
  only:
  - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
deploy:
  provider: s3
  access_key_id: AKIAIT6QYRBBK7UKNRCQ
  secret_access_key:
    secure: OvMzoSS16Wnc1rPo3dcpbJo863C/ljylg+gTpGVTP7QOLjMO+26jkQUKZ7nTWhj9nuDxpdsG8PktO3HAvzoMLIntr1vatPyJxkeuIQsfvbSsRkPNUf8DakuLS3AiHbQ3oP6UUXqNI8lUS7DJHulTFSj7kMSQbuZz1WQOW3/BwqU=
  skip_cleanup: true
  bucket: aslearth.com
  endpoint: aslearth.com.s3-website-us-east-1.amazonaws.com
  region: us-east-1
  acl: public_read
  local-dir: _site
