# Site wide configuration

title:            Atmospheric Spectroscopy Laboratory
locale:           en_US
#url:              http://asl.umbc.edu
url:		   http://aslearth.com
#url:              http://strow.github.io
#url:             http://localhost:4000

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: ASL Team
  avatar: JCET_logo_small.jpg
  bio:  "L. Strow<br>S. Machado<br>H. Motteler<br>C. Hepplewhite<br>A. Tangborn<br>P. Schou"
  email: strow@umbc.edu
  disqus-shortname: aslumbc
  twitter: 
  facebook: 
  google: 
    plus: u/0/114875109936617183653
    analytics: 
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: strow
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
exclude: [vendor]
